import type { RepoSnapshot } from './domain'

export const repositories: RepoSnapshot[] = [
  {
    owner: 'openforge',
    name: 'atlas-core',
    description: 'Policy-aware workflow engine for small maintainer teams.',
    stars: 1840,
    openIssues: 41,
    openPullRequests: 9,
    staleIssues: 7,
    unansweredIssues: 5,
    failingChecks: 1,
    daysSinceRelease: 38,
    daysSinceCommit: 1,
    securityPolicy: true,
    ciConfigured: true,
    dependencyAlerts: 2,
    releaseCandidate: 'v0.8.0',
    work: [
      {
        id: 'ISS-314',
        type: 'issue',
        title: 'Regression in workspace cache invalidation',
        ageDays: 6,
        severity: 'risk',
        label: 'bug',
      },
      {
        id: 'PR-88',
        type: 'pull-request',
        title: 'Add deterministic replay fixtures',
        ageDays: 3,
        severity: 'healthy',
        label: 'tests',
      },
      {
        id: 'SEC-12',
        type: 'security',
        title: 'Review token redaction in debug traces',
        ageDays: 2,
        severity: 'watch',
        label: 'security',
      },
    ],
  },
  {
    owner: 'maintainer-labs',
    name: 'signalpack',
    description: 'Repository health signals exported as portable JSON facts.',
    stars: 612,
    openIssues: 18,
    openPullRequests: 4,
    staleIssues: 2,
    unansweredIssues: 1,
    failingChecks: 0,
    daysSinceRelease: 21,
    daysSinceCommit: 0,
    securityPolicy: true,
    ciConfigured: true,
    dependencyAlerts: 0,
    releaseCandidate: 'v1.4.2',
    work: [
      {
        id: 'REL-19',
        type: 'release',
        title: 'Patch release after parser fix',
        ageDays: 1,
        severity: 'healthy',
        label: 'release',
      },
      {
        id: 'PR-71',
        type: 'pull-request',
        title: 'Document custom signal adapters',
        ageDays: 5,
        severity: 'watch',
        label: 'docs',
      },
    ],
  },
  {
    owner: 'civic-oss',
    name: 'grantwatch',
    description: 'Open grants tracker for volunteer civic technology groups.',
    stars: 329,
    openIssues: 63,
    openPullRequests: 16,
    staleIssues: 21,
    unansweredIssues: 13,
    failingChecks: 3,
    daysSinceRelease: 94,
    daysSinceCommit: 12,
    securityPolicy: false,
    ciConfigured: true,
    dependencyAlerts: 5,
    releaseCandidate: 'v0.3.0',
    work: [
      {
        id: 'ISS-120',
        type: 'issue',
        title: 'Import flow fails on duplicate grant IDs',
        ageDays: 25,
        severity: 'risk',
        label: 'bug',
      },
      {
        id: 'PR-44',
        type: 'pull-request',
        title: 'Replace deprecated CSV parser',
        ageDays: 18,
        severity: 'risk',
        label: 'deps',
      },
      {
        id: 'SEC-4',
        type: 'security',
        title: 'Add disclosure policy before next release',
        ageDays: 32,
        severity: 'risk',
        label: 'security',
      },
    ],
  },
]
